name = "gtemplate"
version = "1.0.1"
description = "Basic templating"

licences = ["MIT"]
repository = { type = "github", user = "ObamaTheLlama114", repo = "gtemplate" }
gleam = ">= 1.11.1"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
